//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectFourClient.ConnectFourService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserExistsFault", Namespace="http://schemas.datacontract.org/2004/07/ConnectFourServer")]
    [System.SerializableAttribute()]
    public partial class UserExistsFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAlreadyLoggedInFault", Namespace="http://schemas.datacontract.org/2004/07/ConnectFourServer")]
    [System.SerializableAttribute()]
    public partial class UserAlreadyLoggedInFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/ConnectFourServer")]
    [System.SerializableAttribute()]
    public partial class UserNotFoundFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayersDetails", Namespace="http://schemas.datacontract.org/2004/07/ConnectFourDBCore")]
    [System.SerializableAttribute()]
    public partial class PlayersDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numOfGamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numOfLosesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numOfPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numOfWinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numOfGames {
            get {
                return this.numOfGamesField;
            }
            set {
                if ((this.numOfGamesField.Equals(value) != true)) {
                    this.numOfGamesField = value;
                    this.RaisePropertyChanged("numOfGames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numOfLoses {
            get {
                return this.numOfLosesField;
            }
            set {
                if ((this.numOfLosesField.Equals(value) != true)) {
                    this.numOfLosesField = value;
                    this.RaisePropertyChanged("numOfLoses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numOfPoints {
            get {
                return this.numOfPointsField;
            }
            set {
                if ((this.numOfPointsField.Equals(value) != true)) {
                    this.numOfPointsField = value;
                    this.RaisePropertyChanged("numOfPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numOfWins {
            get {
                return this.numOfWinsField;
            }
            set {
                if ((this.numOfWinsField.Equals(value) != true)) {
                    this.numOfWinsField = value;
                    this.RaisePropertyChanged("numOfWins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameDetails", Namespace="http://schemas.datacontract.org/2004/07/ConnectFourDBCore")]
    [System.SerializableAttribute()]
    public partial class GameDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Player1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Player2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WinnerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Player1 {
            get {
                return this.Player1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Player1Field, value) != true)) {
                    this.Player1Field = value;
                    this.RaisePropertyChanged("Player1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Player2 {
            get {
                return this.Player2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Player2Field, value) != true)) {
                    this.Player2Field = value;
                    this.RaisePropertyChanged("Player2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Winner {
            get {
                return this.WinnerField;
            }
            set {
                if ((object.ReferenceEquals(this.WinnerField, value) != true)) {
                    this.WinnerField = value;
                    this.RaisePropertyChanged("Winner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayingGames", Namespace="http://schemas.datacontract.org/2004/07/ConnectFourServer")]
    [System.SerializableAttribute()]
    public partial class PlayingGames : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string player1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string player2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime startTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string player1 {
            get {
                return this.player1Field;
            }
            set {
                if ((object.ReferenceEquals(this.player1Field, value) != true)) {
                    this.player1Field = value;
                    this.RaisePropertyChanged("player1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string player2 {
            get {
                return this.player2Field;
            }
            set {
                if ((object.ReferenceEquals(this.player2Field, value) != true)) {
                    this.player2Field = value;
                    this.RaisePropertyChanged("player2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startTime {
            get {
                return this.startTimeField;
            }
            set {
                if ((this.startTimeField.Equals(value) != true)) {
                    this.startTimeField = value;
                    this.RaisePropertyChanged("startTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertResult", Namespace="http://schemas.datacontract.org/2004/07/ConnectFourServer")]
    [System.SerializableAttribute()]
    public partial class InsertResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConnectFourClient.ConnectFourService.MOVE_RESULT Move_resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Row_indexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConnectFourClient.ConnectFourService.MOVE_RESULT Move_result {
            get {
                return this.Move_resultField;
            }
            set {
                if ((this.Move_resultField.Equals(value) != true)) {
                    this.Move_resultField = value;
                    this.RaisePropertyChanged("Move_result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Row_index {
            get {
                return this.Row_indexField;
            }
            set {
                if ((this.Row_indexField.Equals(value) != true)) {
                    this.Row_indexField = value;
                    this.RaisePropertyChanged("Row_index");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MOVE_RESULT", Namespace="http://schemas.datacontract.org/2004/07/ConnectFourServer")]
    public enum MOVE_RESULT : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Win = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Draw = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nothing = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConnectFourService.IConnectFourService", CallbackContract=typeof(ConnectFourClient.ConnectFourService.IConnectFourServiceCallback))]
    public interface IConnectFourService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/register", ReplyAction="http://tempuri.org/IConnectFourService/registerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConnectFourClient.ConnectFourService.UserExistsFault), Action="http://tempuri.org/IConnectFourService/registerUserExistsFaultFault", Name="UserExistsFault", Namespace="http://schemas.datacontract.org/2004/07/ConnectFourServer")]
        void register(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/register", ReplyAction="http://tempuri.org/IConnectFourService/registerResponse")]
        System.Threading.Tasks.Task registerAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/login", ReplyAction="http://tempuri.org/IConnectFourService/loginResponse")]
        bool login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/login", ReplyAction="http://tempuri.org/IConnectFourService/loginResponse")]
        System.Threading.Tasks.Task<bool> loginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/Connect", ReplyAction="http://tempuri.org/IConnectFourService/ConnectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConnectFourClient.ConnectFourService.UserAlreadyLoggedInFault), Action="http://tempuri.org/IConnectFourService/ConnectUserAlreadyLoggedInFaultFault", Name="UserAlreadyLoggedInFault", Namespace="http://schemas.datacontract.org/2004/07/ConnectFourServer")]
        void Connect(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/Connect", ReplyAction="http://tempuri.org/IConnectFourService/ConnectResponse")]
        System.Threading.Tasks.Task ConnectAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/Disconnect", ReplyAction="http://tempuri.org/IConnectFourService/DisconnectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConnectFourClient.ConnectFourService.UserNotFoundFault), Action="http://tempuri.org/IConnectFourService/DisconnectUserNotFoundFaultFault", Name="UserNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/ConnectFourServer")]
        void Disconnect(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/Disconnect", ReplyAction="http://tempuri.org/IConnectFourService/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/getPlayers", ReplyAction="http://tempuri.org/IConnectFourService/getPlayersResponse")]
        ConnectFourClient.ConnectFourService.PlayersDetails[] getPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/getPlayers", ReplyAction="http://tempuri.org/IConnectFourService/getPlayersResponse")]
        System.Threading.Tasks.Task<ConnectFourClient.ConnectFourService.PlayersDetails[]> getPlayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/getPlayerDetails", ReplyAction="http://tempuri.org/IConnectFourService/getPlayerDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConnectFourClient.ConnectFourService.UserNotFoundFault), Action="http://tempuri.org/IConnectFourService/getPlayerDetailsUserNotFoundFaultFault", Name="UserNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/ConnectFourServer")]
        ConnectFourClient.ConnectFourService.PlayersDetails getPlayerDetails(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/getPlayerDetails", ReplyAction="http://tempuri.org/IConnectFourService/getPlayerDetailsResponse")]
        System.Threading.Tasks.Task<ConnectFourClient.ConnectFourService.PlayersDetails> getPlayerDetailsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/getGames", ReplyAction="http://tempuri.org/IConnectFourService/getGamesResponse")]
        ConnectFourClient.ConnectFourService.GameDetails[] getGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/getGames", ReplyAction="http://tempuri.org/IConnectFourService/getGamesResponse")]
        System.Threading.Tasks.Task<ConnectFourClient.ConnectFourService.GameDetails[]> getGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/getCurrentGames", ReplyAction="http://tempuri.org/IConnectFourService/getCurrentGamesResponse")]
        ConnectFourClient.ConnectFourService.PlayingGames[] getCurrentGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/getCurrentGames", ReplyAction="http://tempuri.org/IConnectFourService/getCurrentGamesResponse")]
        System.Threading.Tasks.Task<ConnectFourClient.ConnectFourService.PlayingGames[]> getCurrentGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/SendRequestForGameToUser", ReplyAction="http://tempuri.org/IConnectFourService/SendRequestForGameToUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConnectFourClient.ConnectFourService.UserNotFoundFault), Action="http://tempuri.org/IConnectFourService/SendRequestForGameToUserUserNotFoundFaultF" +
            "ault", Name="UserNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/ConnectFourServer")]
        bool SendRequestForGameToUser(string opponentUserName, string myUserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/SendRequestForGameToUser", ReplyAction="http://tempuri.org/IConnectFourService/SendRequestForGameToUserResponse")]
        System.Threading.Tasks.Task<bool> SendRequestForGameToUserAsync(string opponentUserName, string myUserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/InitGame", ReplyAction="http://tempuri.org/IConnectFourService/InitGameResponse")]
        int InitGame(string player1, string player2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/InitGame", ReplyAction="http://tempuri.org/IConnectFourService/InitGameResponse")]
        System.Threading.Tasks.Task<int> InitGameAsync(string player1, string player2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/IsMyTurn", ReplyAction="http://tempuri.org/IConnectFourService/IsMyTurnResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConnectFourClient.ConnectFourService.UserNotFoundFault), Action="http://tempuri.org/IConnectFourService/IsMyTurnUserNotFoundFaultFault", Name="UserNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/ConnectFourServer")]
        bool IsMyTurn(string playerName, int gameId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/IsMyTurn", ReplyAction="http://tempuri.org/IConnectFourService/IsMyTurnResponse")]
        System.Threading.Tasks.Task<bool> IsMyTurnAsync(string playerName, int gameId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/Insert", ReplyAction="http://tempuri.org/IConnectFourService/InsertResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConnectFourClient.ConnectFourService.UserNotFoundFault), Action="http://tempuri.org/IConnectFourService/InsertUserNotFoundFaultFault", Name="UserNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/ConnectFourServer")]
        ConnectFourClient.ConnectFourService.InsertResult Insert(int column, string playerName, int gameId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/Insert", ReplyAction="http://tempuri.org/IConnectFourService/InsertResponse")]
        System.Threading.Tasks.Task<ConnectFourClient.ConnectFourService.InsertResult> InsertAsync(int column, string playerName, int gameId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/GiveupGame", ReplyAction="http://tempuri.org/IConnectFourService/GiveupGameResponse")]
        void GiveupGame(string playerName, int gameId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/GiveupGame", ReplyAction="http://tempuri.org/IConnectFourService/GiveupGameResponse")]
        System.Threading.Tasks.Task GiveupGameAsync(string playerName, int gameId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConnectFourServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IConnectFourService/addUsersToList")]
        void addUsersToList(string[] newUser);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IConnectFourService/removeUsersFromList")]
        void removeUsersFromList(string connclients);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectFourService/sendGameRequestToUser", ReplyAction="http://tempuri.org/IConnectFourService/sendGameRequestToUserResponse")]
        bool sendGameRequestToUser(string fromUser);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IConnectFourService/updateCell")]
        void updateCell(int row, int col, ConnectFourClient.ConnectFourService.MOVE_RESULT move_result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IConnectFourService/sendGameId")]
        void sendGameId(int gameId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IConnectFourService/annouceWinnerBecauseOtherPlayerLeft")]
        void annouceWinnerBecauseOtherPlayerLeft();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConnectFourServiceChannel : ConnectFourClient.ConnectFourService.IConnectFourService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConnectFourServiceClient : System.ServiceModel.DuplexClientBase<ConnectFourClient.ConnectFourService.IConnectFourService>, ConnectFourClient.ConnectFourService.IConnectFourService {
        
        public ConnectFourServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ConnectFourServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ConnectFourServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ConnectFourServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ConnectFourServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void register(string username, string password) {
            base.Channel.register(username, password);
        }
        
        public System.Threading.Tasks.Task registerAsync(string username, string password) {
            return base.Channel.registerAsync(username, password);
        }
        
        public bool login(string username, string password) {
            return base.Channel.login(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> loginAsync(string username, string password) {
            return base.Channel.loginAsync(username, password);
        }
        
        public void Connect(string username) {
            base.Channel.Connect(username);
        }
        
        public System.Threading.Tasks.Task ConnectAsync(string username) {
            return base.Channel.ConnectAsync(username);
        }
        
        public void Disconnect(string userName) {
            base.Channel.Disconnect(userName);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(string userName) {
            return base.Channel.DisconnectAsync(userName);
        }
        
        public ConnectFourClient.ConnectFourService.PlayersDetails[] getPlayers() {
            return base.Channel.getPlayers();
        }
        
        public System.Threading.Tasks.Task<ConnectFourClient.ConnectFourService.PlayersDetails[]> getPlayersAsync() {
            return base.Channel.getPlayersAsync();
        }
        
        public ConnectFourClient.ConnectFourService.PlayersDetails getPlayerDetails(string username) {
            return base.Channel.getPlayerDetails(username);
        }
        
        public System.Threading.Tasks.Task<ConnectFourClient.ConnectFourService.PlayersDetails> getPlayerDetailsAsync(string username) {
            return base.Channel.getPlayerDetailsAsync(username);
        }
        
        public ConnectFourClient.ConnectFourService.GameDetails[] getGames() {
            return base.Channel.getGames();
        }
        
        public System.Threading.Tasks.Task<ConnectFourClient.ConnectFourService.GameDetails[]> getGamesAsync() {
            return base.Channel.getGamesAsync();
        }
        
        public ConnectFourClient.ConnectFourService.PlayingGames[] getCurrentGames() {
            return base.Channel.getCurrentGames();
        }
        
        public System.Threading.Tasks.Task<ConnectFourClient.ConnectFourService.PlayingGames[]> getCurrentGamesAsync() {
            return base.Channel.getCurrentGamesAsync();
        }
        
        public bool SendRequestForGameToUser(string opponentUserName, string myUserName) {
            return base.Channel.SendRequestForGameToUser(opponentUserName, myUserName);
        }
        
        public System.Threading.Tasks.Task<bool> SendRequestForGameToUserAsync(string opponentUserName, string myUserName) {
            return base.Channel.SendRequestForGameToUserAsync(opponentUserName, myUserName);
        }
        
        public int InitGame(string player1, string player2) {
            return base.Channel.InitGame(player1, player2);
        }
        
        public System.Threading.Tasks.Task<int> InitGameAsync(string player1, string player2) {
            return base.Channel.InitGameAsync(player1, player2);
        }
        
        public bool IsMyTurn(string playerName, int gameId) {
            return base.Channel.IsMyTurn(playerName, gameId);
        }
        
        public System.Threading.Tasks.Task<bool> IsMyTurnAsync(string playerName, int gameId) {
            return base.Channel.IsMyTurnAsync(playerName, gameId);
        }
        
        public ConnectFourClient.ConnectFourService.InsertResult Insert(int column, string playerName, int gameId) {
            return base.Channel.Insert(column, playerName, gameId);
        }
        
        public System.Threading.Tasks.Task<ConnectFourClient.ConnectFourService.InsertResult> InsertAsync(int column, string playerName, int gameId) {
            return base.Channel.InsertAsync(column, playerName, gameId);
        }
        
        public void GiveupGame(string playerName, int gameId) {
            base.Channel.GiveupGame(playerName, gameId);
        }
        
        public System.Threading.Tasks.Task GiveupGameAsync(string playerName, int gameId) {
            return base.Channel.GiveupGameAsync(playerName, gameId);
        }
    }
}
